const menu=document.querySelector('.menu'),nav=document.querySelector('.nav nav');
const portfolioNav=[...document.querySelectorAll('.nav nav a')].find(a=>a.textContent.trim()==='Portfolio');
if(portfolioNav){portfolioNav.href='portfolio.html';portfolioNav.removeAttribute('data-filter')}
menu?.addEventListener('click',()=>{nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='76px';nav.style.left='0';nav.style.right='0';nav.style.padding='25px 7vw';nav.style.flexDirection='column';nav.style.background='#090909'});

document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const filter=btn.dataset.filter;document.querySelectorAll('.gallery figure').forEach(card=>{card.style.display=filter==='all'||card.dataset.cat===filter?'block':'none'})}));
const form=document.getElementById('bookingForm');form?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const name=data.get('name'),phone=data.get('phone'),service=data.get('service'),date=data.get('date')||'Not specified',message=data.get('message')||'Not specified';const text=`Hi AK MEDIA, I would like to make an enquiry.%0A%0AName: ${encodeURIComponent(name)}%0APhone: ${encodeURIComponent(phone)}%0AService: ${encodeURIComponent(service)}%0AEvent date: ${encodeURIComponent(date)}%0ADetails: ${encodeURIComponent(message)}`;window.open(`https://wa.me/918778466181?text=${text}`,'_blank')});

const contact=document.getElementById('contact');
if(contact && !document.getElementById('business-segments')){
 const s=document.createElement('section');s.id='business-segments';s.className='section business-segments';
 s.innerHTML=`<div class="section-head"><div><p class="eyebrow">MORE FROM AK MEDIA</p><h2>Our <em>Business Segments</em></h2></div><p>Beyond photography, AK MEDIA provides connectivity, digital services and professional printing solutions under one roof.</p></div><div class="segment-grid"><article><div class="segment-icon">◉</div><p class="segment-no">01</p><h3>Internet & Cable TV Network</h3><p>Reliable internet connectivity and cable/IPTV entertainment services for homes and businesses.</p><ul><li>TICFIBER internet services</li><li>TCCL cable / IPTV network</li><li>600+ channel options</li><li>20+ OTT entertainment options for eligible packages</li><li>Free router on selected plans</li><li>Free maintenance & 24/7 service support</li><li>Low-cost installation options</li></ul><a href="https://wa.me/918778466181?text=Hi%20AK%20MEDIA%2C%20I%20need%20Internet%20%2F%20Cable%20TV%20service." target="_blank">Enquire for Connection →</a></article><article><div class="segment-icon">⌘</div><p class="segment-no">02</p><h3>Government-Aided eServices</h3><p>Convenient digital assistance for eligible government and citizen e-services from a local service point.</p><ul><li>Online application assistance</li><li>Digital form filling</li><li>Document scanning & uploading</li><li>Print / photocopy support</li><li>Citizen service assistance</li><li>Guidance for online government portals</li></ul><a href="https://wa.me/918778466181?text=Hi%20AK%20MEDIA%2C%20I%20need%20Government%20eService%20assistance." target="_blank">Enquire for eServices →</a></article><article><div class="segment-icon">▣</div><p class="segment-no">03</p><h3>Digital Printing Works</h3><p>Professional digital printing and creative production for personal, business and event requirements.</p><ul><li>Photo printing & enlargements</li><li>Posters & flyers</li><li>Business cards & brochures</li><li>Invitation & event printing</li><li>Photo frames & acrylic prints</li><li>Custom promotional materials</li></ul><a href="https://wa.me/918778466181?text=Hi%20AK%20MEDIA%2C%20I%20need%20Digital%20Printing%20service." target="_blank">Get Printing Quote →</a></article></div><div class="segment-cta"><strong>ONE BRAND • MULTIPLE SERVICES</strong><span>Media • Connectivity • eServices • Printing</span></div></section>`;
 contact.parentNode.insertBefore(s,contact);
}
if(!document.getElementById('business-segment-style')){const st=document.createElement('style');st.id='business-segment-style';st.textContent=`.business-segments{background:#f2eee5}.segment-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.segment-grid article{background:#fff;border:1px solid #ddd4c2;padding:32px 28px;box-shadow:0 12px 30px #00000008;transition:.3s}.segment-grid article:hover{transform:translateY(-5px);box-shadow:0 18px 38px #00000012}.segment-icon{width:52px;height:52px;border:1px solid #c9a66b;border-radius:50%;display:grid;place-items:center;color:#b78322;font-size:22px}.segment-no{font-size:9px;letter-spacing:.2em;color:#b78322;margin-top:24px}.segment-grid h3{font:600 27px 'Playfair Display',Georgia,serif;margin:8px 0 12px}.segment-grid article>p:not(.segment-no){font-size:13px;line-height:1.7;color:#777}.segment-grid ul{list-style:none;padding:0;color:#555;font-size:12px;line-height:1.9}.segment-grid li:before{content:'✓';color:#b78322;margin-right:8px}.segment-grid a{display:inline-block;margin-top:14px;color:#153b28;font-size:10px;text-transform:uppercase;letter-spacing:.1em;border-bottom:1px solid #c9a66b;padding-bottom:6px}.segment-cta{margin-top:18px;background:#111;color:#fff;padding:22px 26px;display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap;font-size:11px;letter-spacing:.1em}@media(max-width:900px){.segment-grid{grid-template-columns:1fr}}`;document.head.appendChild(st)}

// Keep Internet & Cable section immediately after Portfolio and make its posters compact.
const internetSection=document.getElementById('internet');
const portfolioSection=document.getElementById('portfolio');
if(internetSection && portfolioSection){portfolioSection.after(internetSection)}
if(!document.getElementById('internet-layout-style')){const st=document.createElement('style');st.id='internet-layout-style';st.textContent=`.internet-section{padding:75px 8vw;background:#eef2f7}.internet-wrap{max-width:1200px;margin:0 auto}.internet-intro{max-width:760px}.internet-intro h2{font-size:clamp(42px,5vw,68px)}.internet-intro>p:not(.eyebrow){font-size:14px;line-height:1.7;color:#666}.internet-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.internet-btn{display:inline-block;padding:12px 18px;background:#111;color:#fff;font-size:10px;text-transform:uppercase;letter-spacing:.1em}.internet-btn.outline{background:transparent;color:#111;border:1px solid #aaa}.internet-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin-top:35px;max-width:820px;margin-left:auto;margin-right:auto}.internet-gallery figure{margin:0;background:#fff;border:1px solid #ddd;overflow:hidden;box-shadow:0 8px 25px #0000000d}.internet-gallery img{display:block;width:100%;height:280px;object-fit:contain;background:#f4f4f4}.internet-gallery figcaption{padding:14px 16px;display:flex;flex-direction:column;gap:5px}.internet-gallery figcaption strong{font-size:11px;letter-spacing:.08em}.internet-gallery figcaption span{font-size:10px;color:#777}.internet-features{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:#d8dde5;margin-top:28px}.internet-features div{background:#fff;padding:20px}.internet-features b{display:block;font-size:20px}.internet-features span{font-size:10px;color:#777}.internet-note{font-size:10px;color:#888;margin-top:15px}@media(max-width:900px){.internet-section{padding:60px 7vw}.internet-gallery{grid-template-columns:1fr;max-width:500px}.internet-gallery img{height:250px}.internet-features{grid-template-columns:1fr 1fr}}`;document.head.appendChild(st)}

// Add three separate offer cards after Portfolio and before Packages.
if(!document.getElementById('offers')){
 const offers=document.createElement('section');offers.id='offers';offers.className='section offers-section';
 offers.innerHTML=`<div class="section-head"><div><p class="eyebrow">LATEST OFFERS</p><h2>Special <em>Offers</em></h2></div><p>Explore our current AK MEDIA promotions. Each offer is presented separately for easy viewing and enquiry.</p></div><div class="offers-grid"><article class="offer-card"><img src="assets/offer-photography.jpg" alt="AK MEDIA Photography Booking Offer"><div class="offer-card-body"><p class="offer-label">PHOTOGRAPHY</p><h3>Photography Booking</h3><p>Booking open for next season • Packages from ₹29,999 • 48 Hours Album Delivery • Video Edit Delivery • Free Photo Frame + Calendar 2027.</p><a href="https://wa.me/918778466181?text=Hi%20AK%20MEDIA%2C%20I%20am%20interested%20in%20the%20Photography%20Booking%20Offer." target="_blank">WhatsApp Enquiry →</a></div></article><article class="offer-card"><img src="assets/offer-video-editing.jpg" alt="AK MEDIA Video Editing Offer"><div class="offer-card-body"><p class="offer-label">VIDEO EDITING</p><h3>Professional Video Editing</h3><p>Starts from ₹399 • Wedding edits • Reels & Shorts • Birthday videos • Promo videos • YouTube edits • Cinematic edits • Fast turnaround.</p><a href="https://wa.me/918778466181?text=Hi%20AK%20MEDIA%2C%20I%20am%20interested%20in%20the%20Video%20Editing%20Offer." target="_blank">Get Editing Quote →</a></div></article><article class="offer-card"><img src="assets/offer-varalakshmi-pooja.jpg" alt="AK MEDIA Varalakshmi Pooja Photography Offer"><div class="offer-card-body"><p class="offer-label">SPECIAL EVENT OFFER</p><h3>Varalakshmi Pooja Offer</h3><p>1 Hour • ₹1,500 • Unlimited Photos • 10 Photos Edited • Accommodation separate. Book now and capture the divine moments beautifully.</p><a href="https://wa.me/918778466181?text=Hi%20AK%20MEDIA%2C%20I%20am%20interested%20in%20the%20Varalakshmi%20Pooja%20Offer." target="_blank">Book This Offer →</a></div></article></div>`;
 const packages=document.getElementById('packages');
 if(portfolioSection&&packages)portfolioSection.after(offers); else if(packages)packages.before(offers);
}
if(!document.getElementById('offers-style')){const st=document.createElement('style');st.id='offers-style';st.textContent=`.offers-section{background:#fff}.offers-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.offer-card{background:#fff;border:1px solid #ddd;overflow:hidden;box-shadow:0 12px 35px #00000010;transition:.3s}.offer-card:hover{transform:translateY(-5px);box-shadow:0 18px 42px #00000018}.offer-card>img{display:block;width:100%;height:330px;object-fit:contain;background:#f4f4f4}.offer-card-body{padding:22px}.offer-label{font-size:9px;letter-spacing:.18em;color:#b78322;font-weight:700}.offer-card h3{font:600 27px 'Playfair Display',Georgia,serif;margin:10px 0}.offer-card-body>p:not(.offer-label){font-size:12px;line-height:1.7;color:#777}.offer-card a{display:inline-block;margin-top:12px;color:#111;font-size:10px;text-transform:uppercase;letter-spacing:.1em;border-bottom:1px solid #c9a66b;padding-bottom:6px}@media(max-width:900px){.offers-grid{grid-template-columns:1fr}.offer-card>img{height:420px}}`;document.head.appendChild(st)}

document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{if(window.innerWidth<=900&&nav)nav.style.display='none'}));